lang: en
timezone: Asia/Seoul

title: "Mingi's IT Blog"
tagline: "Notes on Network, Security & Infra Ops"
description: >-
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

url: "https://leemingi6901.github.io"

github:
  username: Leemingi6901

social:
  name: "Mingi LEE"
  email: leemingi69012@gmail.com
  links:
    - https://twitter.com/leemingi6901
    - https://github.com/Leemingi6901

theme_mode: light

toc: true
paginate: 10
baseurl: ""

avatar: /assets/img/profile.png

comments:
  provider: disqus
  disqus:
    shortname: mingi-blog
  utterances:
    repo: Leemingi6901/Leemingi6901.github.io
    issue_term: pathname
  giscus:
    repo: Leemingi6901/Leemingi6901.github.io
    repo_id: dummy-repo-id
    category: General
    category_id: dummy-category-id
    mapping: pathname
    strict: 0
    input_position: bottom
    lang: en
    reactions_enabled: 1

assets:
  self_host:
    enabled: false
    env: production

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: []

analytics:
  google:
    id: G-XXXXXXXXXX
  goatcounter:
    id: mingi-blog
  umami:
    id: dummy-umami-id
    domain: analytics.mingi.com
  matomo:
    id: dummy-matomo-id
    domain: matomo.mingi.com
  cloudflare:
    id: dummy-cloudflare-id
  fathom:
    id: dummy-fathom-id

pageviews:
  provider: goatcounter

webmaster_verifications:
  google: dummy-google-code
  bing: dummy-bing-code
  alexa: dummy-alexa-code
  yandex: dummy-yandex-code
  baidu: dummy-baidu-code
  facebook: dummy-facebook-code

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
