lang: ko
timezone: Asia/Seoul

title: Mingi's Infra Blog
tagline: Notes on Network, Security & Infra Ops
description: >-
  A tech blog focused on real-world infrastructure & security operations.

url: "https://leemingi6901.github.io"

github:
  username: Leemingi6901

twitter:
  username: leemingi6901

social:
  name: Mingi Lee (Daniel)
  email: leemingi69012@gmail.com
  links:
    - https://twitter.com/leemingi6901
    - https://github.com/Leemingi6901

theme_mode: light

avatar: /assets/img/profile.png

toc: true

paginate: 10

baseurl: ""

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
